// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikijqwjnejmsgysstolq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlraWpxd2puZWptc2d5c3N0b2xxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2ODk4ODAsImV4cCI6MjA3MTI2NTg4MH0.Y2pcJIzOBlb4fPUc9_V8huzc4ZBjfPCb7BjX-ngn7xs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});